## Production Environment Configuration
app.url=https://www.amazon.in
browser=chrome
headless=true
implicit.wait=20
explicit.wait=25
page.load.timeout=40

## Driver Options
driver.maximize=false
driver.notifications=false
driver.incognito=true

## Logging
log.level=WARN
log.file.path=logs/prod.log
