## Staging Environment Configuration
app.url=https://staging.amazon.in
browser=chrome
headless=false
implicit.wait=15
explicit.wait=20
page.load.timeout=30

## Driver Options
driver.maximize=true
driver.notifications=false
driver.incognito=false

## Logging
log.level=INFO
log.file.path=logs/staging.log
